# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  branches:
    '{master,ins-104,cmt-104,ins-103,cmt-103,ins-102,cmt-102}':
    - step:
        script: # This will pull all branches from bitbucket and push all to github
          - git clone --mirror git@github.com:sf-industries/newport-design-system.git
          - cd newport-design-system.git
          - git remote set-url --push origin git@github.com:vlocityinc/newport-design-system.git
          - git fetch -p origin
          - git push --mirror
